#!/bin/sh

echo -n "Unmounting local filesystems..."

(
DIRS=""
while read DEV DIR TYPE REST; do
    case "$DIR-$TYPE" in
        *-proc|*-sysfs|*-devpts|*-usbfs) ;;
        /-*) ;;
        *-*) DIRS="$DIR $DIRS";;
    esac
done

exec < /dev/null

if [ -n "$DIRS" ]; then
    /bin/umount -r -f -l $DIRS
fi
) < /etc/mtab

echo "done."

/bin/mount -n -o remount,ro /

: exit 0
