#!/bin/sh

[ -c /dev/urandom ] || exit 0

SEED=/var/lib/urandom/random-seed

if [ -f /proc/sys/kernel/random/poolsize ]; then
	POOLSIZE="`cat /proc/sys/kernel/random/poolsize`"
else
    POOLSIZE=512
fi

case "$1" in
	start|"")
		echo -n "Initializing random number generator... "

		if [ -f $SEED ]; then
			cat $SEED >/dev/urandom
		fi
		rm -f $SEED

		echo "done.";;
	stop)
		echo -n "Saving random seed... "
		umask 077
		if dd if=/dev/urandom of=$SEED bs=$POOLSIZE count=1 >/dev/null 2>&1; then
		    echo "done."
        else
            echo "failed."
        fi
        umask 022;;
	*)
		echo "Usage: urandom {start|stop}" >&2
		exit 1
		;;
esac

: exit 0
