#! /bin/sh
#
# debian.postinst
#
# Version:	debian.postinst  2.85-20  07-Jun-2004  miquels@cistron.nl
#

set -e

case "$1" in
	configure)
		oldver=$2
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0
		;;
esac
umask 022


#
#   TODO: use sysv-rc's update-rc.d instead (which duplicates this code
#   in fact)
#	Function like update-rc.d but simpler & faster.
#	Usage: updatercd basename start|stop NN runlevel .
#
#	Heuristic: use the real update-rc.d if file-rc is detected,
#	or if the /etc/rc2.d directory is not present.
#
updatercd() {

	if [ ! -f /etc/init.d/$1 ]
	then
		return
	fi

	if [ -d /usr/share/file-rc/. ] || [ -d /usr/lib/file-rc/. ] ||
	   [ ! -d /etc/rc2.d/. ]
	then
		update-rc.d "$@" > /dev/null
		return $?
	fi

	base=$1
	shift

	tmp="`echo /etc/rc?.d/[SK]??$base`"
	case "$tmp" in
		"/etc/rc?.d/[SK]??$base")
			;;
		*)
			return
			;;
	esac

	while [ "$1" != "" ]
	do
		if [ "$1" = stop ]
		then
			tlet=K
		else
			tlet=S
		fi
		case "$2" in
			?) lev=0$2 ;;
			*) lev=$2 ;;
		esac
		shift 2
		while [ "$1" != "." ]
		do
			cd /etc/rc$1.d
			ln -s ../init.d/$base $tlet$lev$base
			shift
		done
		shift
	done
}

rm -f /etc/default/rcS
rm -f /etc/rc?.d/[SK]??checkfs.sh /etc/init.d/checkfs.sh
rm -f /etc/rc?.d/[SK]36mountvirtfs
rm -f /etc/rc?.d/[SK]??urandom

#
#	Okay, we could do this with update-rc.d, but that would probably
#	be pretty slow. This way we win some speed.
#	DO NOT FOLLOW THIS EXAMPLE IN OTHER PACKAGES.
#
updatercd mountvirtfs	start 2 S .
updatercd bootlogd	start 5 S .
updatercd checkroot.sh	start 10 S .
updatercd modutils	start 20 S .
updatercd mountall.sh	start 35 S .
updatercd hostname.sh	start 40 S .
updatercd network	start 40 S .
updatercd bootmisc.sh	start 55 S .

#
#	Links in "normal" runlevels.
#
updatercd sendsigs	start 20 0 6 .
updatercd umountfs	start 40 0 6 .
updatercd rmnologin	start 99 2 .
updatercd stop-bootlogd	start 99 2 .

exit 0
